language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t russianreversal/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true russianreversal/docker-react npm run test